### ISSUE TITLE
UnboundLocalError: local variable 'repo_ids' referenced before assignment

### ISSUE THREAD

**Issue by fridex** [samuelmacko/master_thesis#5]
```
Traceback (most recent call last):
--
  | File "/tmp/thesis_app/data_gathering/dataset.py", line 263, in compute_features
  | self.download_all(
  | File "/tmp/thesis_app/data_gathering/dataset.py", line 124, in download_all
  | if s3_handler.bucket_exits_check():
  | File "/tmp/thesis_app/data_gathering/s3_handler.py", line 43, in bucket_exits_check
  | self.client.list_objects(Bucket=_BUCKET_NAME)
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 316, in _api_call
  | return self._make_api_call(operation_name, kwargs)
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 607, in _make_api_call
  | request_dict = self._convert_to_request_dict(
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 653, in _convert_to_request_dict
  | api_params = self._emit_api_params(
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 682, in _emit_api_params
  | self.meta.events.emit(
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/hooks.py", line 356, in emit
  | return self._emitter.emit(aliased_event_name, **kwargs)
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/hooks.py", line 228, in emit
  | return self._emit(event_name, kwargs)
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
  | response = handler(**kwargs)
  | File "/opt/app-root/lib64/python3.8/site-packages/botocore/handlers.py", line 200, in validate_bucket_name
  | if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
  | TypeError: expected string or bytes-like object
  | During handling of the above exception, another exception occurred:
  | Traceback (most recent call last):
  | File "main.py", line 80, in <module>
  | dataset.compute_features(
  | File "/tmp/thesis_app/data_gathering/dataset.py", line 317, in compute_features
  | remaining_ids = repo_ids - computed_ids
  | UnboundLocalError: local variable 'repo_ids' referenced before assignment
```

**Comment by fridex** [comment]
I've just noticed https://github.com/samuelmacko/master_thesis/pull/3 was not merged, causing:

```
  | TypeError: expected string or bytes-like object
```

Updated in #4.
